# Data indexing in pandas

In [5]:
import numpy as np
import pandas as pd

## Reminders on numpy arrays
In the second session, we saw several methods to access and modify values in numpy arrays for instance:

In [7]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Indexing

In [9]:
# TODO: Grab the value 6 in arr
arr[1, 2]

6

### Slicing
Reminder: The syntax for slicing is [start:stop:step]

In [11]:
# TODO: grab the values 5 and 9 in arr
arr[1:, 1]

array([5, 9])

### Masking

In [16]:
# TODO: grab the values greater than threshold in arr_flat
threshold = 2
arr_flat = np.arange(12)
arr_flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:

arr_flat[arr_flat > threshold]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

### Reminder on element-wise boolean operators 
Element-wise boolean operations on NumPy arrays of booleans can be performed using the following characters:
- **and**: arr1 & arr2
- **or** : arr1 | arr2
- **not**: ~arr

In [18]:
arr_flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
# TODO: grab the values greater than threshold_low and lower than threshold_high in arr_flat
threshold_low = 2
threshold_high = 9

In [25]:
arr_flat[(arr_flat > threshold_low) & (arr_flat < threshold_high)]

array([3, 4, 5, 6, 7, 8])

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False])

## Key difference between Pandas objects and NumPy array
Similar ideas will be applied to pandas objects. You must however be aware of some potential issues that arise from the difference between the `explicit` index of pandas `Series` and `DataFrame` i.e. the 'name' of the rows and columns of your object and the `implicit` index or position, similar to NumPy indexing.

For instance, try grabbing the element "cat" for the Series below:

In [31]:
animals = pd.Series(["dog", "cat", "duck"], name="animal", index=[1, 2, 12])
# TODO: Grab the element "cat" from the animals
animals

1      dog
2      cat
12    duck
Name: animal, dtype: object

## Data Selection in Series

As seen previously, a lot of similarities can be found between pandas Series and 1-D dimensional NumPy arrays or dictionaries and both types of indexing can be used.

In [30]:
# Let's create a small pandas Series
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

### Using Series similarly to dictionaries

In [33]:


# TODO: grab the value with index "b" from data
data["b"]

0.5

In [45]:
animals[13] = "cat"
animals[animals == "cat"].index.tolist()

[2, 13]

In [39]:
data[data==.5].index.tolist()

['b']

In [35]:
# TODO: Change the value with index "d" in data to 42
data["d"] = 42
data

a     0.25
b     0.50
c     0.75
d    42.00
dtype: float64

### Using a Series like a one-dimensional array
Slicing can either be done using the **explicit index** of the `Series` or the **implicit integer index** i.e. the position of the elements in the `Series`.

In [48]:
# TODO: Use slicing to select the first three elements of data using its explicit index (the letters)
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [49]:
# TODO: Same thing using its implicit index (similarly to how you would slice a numpy array)
data[1:4]

b     0.50
c     0.75
d    42.00
dtype: float64

### Indexers: loc and iloc
These slicing and indexing conventions can be a source of confusion, in particular when the  explicit indexes of your `Series` are integers:

In [51]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [52]:
# explicit index when indexing
data[1]

'a'

In [53]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

First, the ``loc`` attribute allows indexing and slicing that always references the explicit index:

In [54]:
data.loc[1]

'a'

In [55]:
data.loc[1:3]  # Note that with explicit indexing, the end index is included

1    a
3    b
dtype: object

The ``iloc`` attribute allows indexing and slicing that always references the implicit Python-style index:

In [56]:
data.iloc[1]

'b'

In [57]:
data.iloc[1:3]

3    b
5    c
dtype: object

### Masking
Note that similarly to NumPy arrays, pandas `Series` can be filtered using masking.

Filter the following `Series` to keep only the values greater than threshold:

In [59]:
threshold = .6
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])

data[data > threshold]


c    0.75
d    1.00
dtype: float64

## Data Selection in a `DataFrame`
Recall that a `DataFrame` acts in some ways similarly to a dictionary of `Series` and in others similarly to a 2-dimensional NumPy array.

Lets create a `DataFrame`:

In [60]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

### Accessing the `Series` composing a `DataFrame`
The `Series` composing a `DataFrame` can be accessed using a dictionary-like or attribute-like syntax:

In [62]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [63]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Treating a `DataFrame` as a 2-dimensional array
The raw underlying data of a `DataFrame` can be accessed using the `values` attribute:

In [65]:
data.values

array([[  423967, 38332521],
       [  695662, 26448193],
       [  141297, 19651127],
       [  170312, 19552860],
       [  149995, 12882135]])

### Using implicit indexing on pandas `DataFrame`
Similarly to pandas `Series`, the `iloc` indexer can be used to extract a part of a `DataFrame` using NumPy-like indexing.

Try it by selecting the even rows of data (reminder, for array slicing, the syntax is *[start:stop:step]*).

In [69]:
# TODO
data.iloc[::2, :]

area       pop
California  423967  38332521
New York    141297  19651127
Illinois    149995  12882135

## Exercises

After loading the small database of avocado production in the US as a DataFrame (adapted from [this](https://www.kaggle.com/neuromusic/avocado-prices) database) solve the following problems:

In [74]:
# Load avocado_simplified.csv file as a DataFrame
avocado_prices = pd.read_csv("avocado_simplified.csv", index_col=0)
avocado_prices.head()

region          type  AveragePrice  Total Volume
0               Albany  conventional      1.348757  1.570061e+07
1               Albany       organic      1.773314  3.671885e+05
2              Atlanta  conventional      1.068817  8.666139e+07
3              Atlanta       organic      1.607101  1.943727e+06
4  BaltimoreWashington  conventional      1.344201  1.307456e+08

Filter the `DataFrame` to only keep rows corresponding to the production of conventional avocados

In [77]:
avocado_prices[avocado_prices["type"] == "conventional"].head(3)

region          type  AveragePrice  Total Volume
0               Albany  conventional      1.348757  1.570061e+07
2              Atlanta  conventional      1.068817  8.666139e+07
4  BaltimoreWashington  conventional      1.344201  1.307456e+08

Find the total volume of avocados produced in the US  

In [80]:
np.sum(avocado_prices["Total Volume"])

9658662411.599998

Find the total volume of avocado produced in Louisville

In [86]:
avocado_prices_louisville = avocado_prices[avocado_prices["region"] == "Louisville"]
np.sum(avocado_prices_louisville["Total Volume"])

16097002.4

Select all rows for which the average price is greater than 2

In [89]:
threshold = 2.
avocado_prices[avocado_prices["AveragePrice"] > threshold]

region     type  AveragePrice  Total Volume
35  HartfordSpringfield  organic      2.229231    1609313.38
57              NewYork  organic      2.053018    8990571.40
85         SanFrancisco  organic      2.211243    3785935.69

Using a weighted average, compute the average price of an avocado in the US:

In [91]:
avocado_prices.head(3)

region          type  AveragePrice  Total Volume
0   Albany  conventional      1.348757   15700611.47
1   Albany       organic      1.773314     367188.50
2  Atlanta  conventional      1.068817   86661391.50

In [93]:
# TODO
def weighted_mean(values, weights):
    """Compute the weighted average of input values using weights.
    
    values and weights must be array-like objects of same length
    """
    return np.sum(values * weights) / np.sum(weights)

weighted_mean(avocado_prices["AveragePrice"], avocado_prices["Total Volume"])


1.1168801506156443

Find the regions producing the smallest and highest volumes of conventional avocado in the US (you should get Syracuse and West):

In [100]:
avocado_prices_conventional = avocado_prices[avocado_prices["type"] == "conventional"]
my_argmin = np.argmin(avocado_prices_conventional["Total Volume"])

In [103]:
avocado_prices_conventional.iloc[my_argmin]["region"]

'Syracuse'

In [104]:
my_argmax = np.argmax(avocado_prices_conventional["Total Volume"])
avocado_prices_conventional.iloc[my_argmax]["region"]

'West'

Note that many more operations can be performed on pandas DataFrame but are a bit off-topic in this brief introduction.

As a bonus exercise, you can for instance try to [combine the groupby and agg methods](https://pandas.pydata.org/pandas-docs/version/0.22.0/generated/pandas.core.groupby.DataFrameGroupBy.agg.html) to generate a `DataFrame` with indexes conventional and organic containing the total volume of avocado produced in the US, split by avocado type.

You should obtain something similar to:


| type            | Total Volume |
|--------------|--------------|
| **conventional** | 9.385999e+09 |
| **organic**    | 2.726631e+08 |

In [22]:
# TODO (optional)