# Introduction to numpy

The code from this notebook is largely inspired by [this tutorial from Stanford University's CS231n course](https://cs231n.github.io/python-numpy-tutorial) about Convolutional Neural Networks for Visual Recognition and [Dataquest's "Data Analyst in Python course"](www.dataquest.io%2Fpath%2Fdata-analyst%2F).


## Doing math with lists
Last week we discussed lists which are a way to store an **ordered collection of objects**, they are however not designed to perform scientific computing in Python. Try for instance the following code: 

In [1]:
my_list = [1., 4., 2.5]
my_list * 3

[1.0, 4.0, 2.5, 1.0, 4.0, 2.5]

In [2]:
my_list = [1., 4., 2.5]
my_list + 1.

TypeError: can only concatenate list (not "float") to list

In [3]:
my_list1 = [1., 4.,  2.5]
my_list2 = [5., 3.1, 6. ]
my_list1 + my_list2

[1.0, 4.0, 2.5, 5.0, 3.1, 6.0]

**Exercise**:
Write the code allowing to:
- Multiply each element of a list by a scalar
- Add a scalar to each element of a list
- Add the elements of two lists of same length

In [ ]:
def multiply_list_by_scalar(my_list, scalar):
    "Multiply each element of my_list by scalar"
    # TODO


multiply_list_by_scalar([1., 4., 2.5], 3)

In [ ]:
def add_scalar_to_list(my_list, scalar):
    "Add scalar to each element of my_list"
    # TODO


add_scalar_to_list([1., 4., 2.5], 1.)

In [125]:
# Bonus here if you use the "zip" function
def add_elements_of_two_lists(my_list1, my_list2):
    "Return a list containing the element-wise sum of two input lists"
    # TODO
    

add_elements_of_two_lists([1., 4.,  2.5], [5., 3.1, 6. ])

## Basic operations using Numpy arrays
[Numpy](https://numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The shape of an array is a tuple of integers giving the size of the array along each dimension.

### Initializing an array from lists 
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
import numpy as np  # np is a common alias for numpy

a = np.array([1, 2, 3])   # Create a 1-dimensional array
a

array([1, 2, 3])

In [10]:
print(type(a))  # This will display <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [7]:
b = np.array([[2., 3.], [0, 1]])  # Create a 2-dimensional array
b

array([[2., 3.],
       [0., 1.]])

In [14]:
# Get the shape of an array
print(a.shape)
print(b.shape)

(3,)
(2, 2)


Different datatypes (integers, float, boolean...) can be stored in a numpy array, see [numpy's documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html) for an extensive list.

In [16]:
# Get the data type of an array
print(a.dtype)
print(b.dtype)

int64
float64


### Alternatives for creating an array

In [16]:
# TODO: Create a 2x3 array filled with 0. 
np.zeros

<function numpy.zeros>

In [ ]:
# TODO: Create a 2x3 array filled with 1. 
np.ones

In [ ]:
# TODO: Create an array with integers from 0 to 9
np.arange

In [ ]:
# Create a 3x3x3 array filled with random values between 0 and 1
np.random.random

In [46]:
# TODO: Create a 2x3 array filled with False 
np.zeros

<function numpy.zeros>

In [ ]:
# TODO: Create a 2x3 array filled with True 
np.ones

And more (np.eye, np.full, np.linspace...)

In [81]:
# 2x2 Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [82]:
# 3x3 array filled with 5
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [83]:
# Array of 5 elements linearly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Accessing elements of a numpy array
Numpy offers several ways to index into arrays.

#### Slicing
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [24]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [25]:
# You can also directly modify a value stored in an array as follows:
a[1, 1] = 42
a

array([[ 1,  2,  3,  4],
       [ 5, 42,  7,  8],
       [ 9, 10, 11, 12]])

#### Mixing integer indexing with slice indexing
You can also mix integer indexing with slice indexing.

**WARNING** Doing so will yield an array of lower rank than the original array !

In [27]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

# Grab column with index 1 from a:
a[:, 1]

array([ 2,  6, 10])

In [29]:
# Note that the resulting array is 1-dimensional
a[:, 1].shape

(3,)

**Exercise**: Select second value of the first and last rows of `a` to obtain a one dimensional array:


In [20]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
# TODO, should return array([ 2, 10])

#### Boolean array indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [56]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [59]:
bool_idx = np.array([False, True, True, False, False])
a[bool_idx]

array([1, 2])

### Dealing with arrays' shape

In [112]:
# Reminder: you can access an array's shape as follows:
a = np.zeros((2, 6))
a.shape

(2, 6)

#### Reshaping
You can reshape an array as follows:

In [95]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
a.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Or alternatively:

In [97]:
np.reshape(a, (2, 6))  # ! Note that we used the tuple (2, 6) here

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [50]:
# TODO: Combine np.arange and the reshape method to generate an array with content:
# [[1,  2,  3,  4],
#  [5,  6,  7,  8],
#  [9, 10, 11, 12]]


### Main operations using one numpy array
#### Array math
Mathematical operations (+, -, *, /, **...) between a numpy array and a scalar are applied to each of their elements:

In [70]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
a + 2.5  # Add 2.5 to each element

array([ 2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5,
       13.5])

In [76]:
a * 5  # Multiply each element by 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [74]:
a ** 3  # each of the elements to the power 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331])

#### Boolean operations
Numpy arrays support the classical boolean operations (==, !=, <, <=, >, >=) that are here applied to each element:

In [63]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
a > 3

array([False, False, False, False,  True,  True,  True,  True])

**Exercise**:

Combine array math, boolean operations and Boolean array indexing to select the values of `a` whose square is bigger than 40 **without using any loop**:

In [22]:
a = np.arange(-10, 10, 2)
# TODO: should return array([-10,  -8,   8])

#### Other useful functions
Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum` (many others such as `mean`, `diff` or `count` are also availble, see [numpy's documentation](https://numpy.org/doc/stable/reference/routines.math.html) for a full list):

In [114]:
a = np.array([[1.5, 2.],
             [2.1, 5.]])
a

array([[1.5, 2. ],
       [2.1, 5. ]])

In [116]:
# Sum all elements of a
np.sum(a)

10.6

In [117]:
# Sum the elements of a along an axis
np.sum(a, axis=1)

array([3.5, 7.1])

In [126]:
# sum can also be called as follows
a.sum()

4.5

### Main operations using two (or more) numpy arrays
#### Mathematical operators on two arrays
Basic element-wise mathematical operations (+, -, /, **...) between two arrays are also available as follows:

In [24]:
a = np.array([1., 1.5, 2.])
b = np.array([2., 1.5, 0.])
a + b

array([3., 3., 2.])

Equivalently, you can call the corresponding numpy function like for instance:

In [122]:
np.add(a, b)

array([3., 3., 2.])

**WARNING** the `*` operator between two arrays corresponds to element-wise multplication, not matrix multiplication (you can use `numpy.dot` for that).

In [26]:
a * b

array([2.  , 2.25, 0.  ])

Many more operations are available in [numpy's documentation](https://numpy.org/doc/stable/reference/routines.math.html)

**Exercise:**
Write a function that computes the euclidean norm of an array along an axis:

In [ ]:
def norm(arr, axis=None):
    """Return the euclidean norm of an array along an axis.
    
    By default (axis=None), return the euclidean norm using all values.
    """
    if axis is None:
        # ...
    else:
        # ...


a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
print(norm(a), axis=1)
print(norm(a))

#### Boolean operations
Boolean operations between two arrays can also be performed as follows (more operations can be found in the [documentation](https://numpy.org/doc/stable/reference/routines.logic.html)):

In [134]:
a = np.array([True, False, True, False])
b = np.array([False, True, True, False])

# a AND b
a & b  # equivalent to np.logical_and(a, b)

array([False, False,  True, False])

In [135]:
# a OR b
a | b  # equivalent to np.logical_or(a, b)

array([ True,  True,  True, False])

In [144]:
# not a
~a  # np.logical_not(a)

array([ True, False,  True, False, False, False,  True,  True, False,
        True, False])

You can find the indexes for which an array of boolean is True by using `np.where` (note the format of the output):

In [34]:
a = np.array([True, False, True, False])
# TODO

**Exercise** Find the indexes where the following array's values switch from False to True **without using any loop**:

In [45]:
a = np.array([False, True, False, True, True, True, False, False, True, False, True])
# TODO: should print out array([ 1,  3,  8, 10])

#### Broadcasting
Broadcasting is a mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array. Numpy broadcasting allows us to perform this kind of computation using only one copy of each array.

In [124]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [10, 11, 12]])

v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### A few tricks that could make your life easier
#### You will never beat numpy's performance by coding a function yourself
If you can avoid a loop by using a numpy function, by all means DO IT.

In [8]:
%%timeit
n = 10000
scalar = 3.2

l = list(range(n))
for i, e in enumerate(l):
    l[i] = e * scalar

1.3 ms ± 49.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%%timeit
l = np.arange(n)
l = scalar * l

24.9 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### Tuples as arguments for specifying shape
Many numpy functions require a tuple to specify the shape of the output, most of the time a `TypeError` will be raised if sevaral integers are directly provided: 

In [99]:
# TODO: correct the following code to get a 3x2 array
np.zeros(3, 2)

TypeError: Cannot interpret '2' as a data type

#### Using -1 and reshape
Using -1 for one dimension allows to directly get the correct shape if the others are specified: 

In [108]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
# TODO: reshape a so that it has 2 rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Using -1 and reshape or np.newaxis to add a new dimension
Sometimes, you will need to artificially add a dimension to an array for instance so that the shape of two arrays match for a particular operation, this can be done as follows:

In [103]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
# Reshape a as a 10x1 array
a.reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [107]:
# Idem using np.newaxis
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### Transposing an array
You can transpose an array by using the `numpy.transpose` function or by calling `array.T`:

In [100]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
a.T  # Equivalent to np.transpose(a)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### A slice is a view into the same data
**WARNING** A slice of an array is a view into the same data, so modifying it will modify the original array:

In [85]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

b = a[:2, 1:3]
# b is now: 
# array([[2, 3],
#        [6, 7]])

a[1, 1] = 42


# b is a view of the same data as the ones in a,
# modifying a also modified b
b 

array([[ 2,  3],
       [42,  7]])

### Exercises
Your are not allowed to use loops !

Swap rows 1 and 2 in the array `arr`

In [63]:
arr = np.arange(9).reshape(3,3)
# TODO
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Write a function allowing to rescale the values of an array:

In [68]:
def rescale_array(arr, new_min=0., new_max=1.):
    "Rescale an array's values between arr_min and arr_max."
    # TODO


arr = np.arange(9).reshape(3,3)
rescale_array(arr, new_min=-1., new_max=1.)
# Should print:
# array([[-1.  , -0.75, -0.5 ],
#        [-0.25,  0.  ,  0.25],
#        [ 0.5 ,  0.75,  1.  ]])

Write a function that replace missing values by a constant:

In [56]:
def replace_nan_by_value(arr, new_value=0.):
    "Replace the nan values in an array by a new value."
    # TODO


arr = np.array([0., 1.5, .75, np.nan, 0., np.nan])
arr

array([0.  , 1.5 , 0.75,  nan, 0.  ,  nan])

Write a function that return the count of unique values in a numpy array:

In [69]:
def count_unique(arr):
    "Return the number of unique values in an array"
    # TODO


arr = np.array([0, 1, 2, 2, 2, 3, 1, 3, 0]).reshape(3, -1)
arr

array([[0, 1, 2],
       [2, 2, 3],
       [1, 3, 0]])